### ISSUE TITLE
RESTClient Host is null (UnknownHostException)

### ISSUE THREAD

**Issue by deratzmann** [MicroShed/microshed-testing#143]
**Describe the bug**
Hi there. I am new to microshed, it is a very promising project, so I tried to code some tests.
Currently I have the problem, that the applications is starting in docker but it seems, that the host is not set in the Object annotated by '@RESTClient'.
Plz see the attached Project. this results in a 
'UnknownHostException: UnknownHostException invoking http://null:0/myapp/myresource/dosth: null'

**To Reproduce**
see project zip

**System information:**
 - OS: [e.g. Linux, Windows, Mac]: windows 10
 - Java Version: [e.g. 8, 11]: 8
 - MicroShed Testing Version: [e.g. 0.4.2]: 0.6.2

**Additional context**
IDE: Netbeans 11.2
[mavenproject7.zip](https://github.com/MicroShed/microshed-testing/files/4163968/mavenproject7.zip)

Thanks for your help. And thanks for your work :)

**Comment by aguibert** [comment]
hi @deratzmann, thanks for reporting this issue. 

I started by added a log4j.properties and an SLF4j test dependency as described here which enabled logging for containers and the important aspects of what's happening in the test as described in the "where are the logs" section of this doc: https://microshed.org/microshed-testing/features/00_Walkthrough.html

The reason why the hostname is null is because the static init block of `SystemtestContainerRunner` which is setting the system properties doesn't run until _after_ the rest client classes get injected. I was able to work around this by setting the system properties in pom.xml like this:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0-M4</version>
    <configuration>
        <systemPropertyVariables>
            <microshed_hostname>localhost</microshed_hostname>
            <microshed_http_port>8080</microshed_http_port>
            <WLP_USR_DIR>${project.build.directory}/openliberty</WLP_USR_DIR>
        </systemPropertyVariables>
        <trimStackTrace>false</trimStackTrace>
    </configuration>
</plugin>
```
While you can do the above to workaround the issue, I think what you are doing is reasonable so I'll add some code in microshed to explicitly trigger init of any shared container configuration _before_ we inject rest clients.

## Additional suggestion
I see that you're not using the Liberty Maven Plugin currently -- I would highly recommend using this for Liberty development. It also has auto-configuration for Microshed, so you don't need to manually set any system properties like `microshed_hostname`.

Have a look at [this OpenLiberty guide](https://openliberty.io/guides/microshed-testing.html), which will walk you through building and testing a Liberty application using the Liberty Maven Plugin + MicroShed

**Comment by deratzmann** [comment]
Thank you!! I'll try that.

**Comment by aguibert** [comment]
hi @deratzmann, version 0.7.1 is now released which should include the fix for this issue
