### ISSUE TITLE
@QuarkusTest collides with @KafkaConsumerConfig/@KafkaProducerConfig

### ISSUE THREAD

**Issue by CrystalMethod** [MicroShed/microshed-testing#181]
**Describe the bug**
Kafka consumer and producer will not be injected into `@QuarkusTest` annotated tests. Fields are null.

**To Reproduce**
```java
@MicroShedTest
@QuarkusTest
@SharedContainerConfig(KafkaTestResourceConfig.class)
public class MyTest {

  @KafkaConsumerConfig(groupId = "my-consumer")
  public static KafkaConsumer<String, String> consumer;

  @KafkaProducerConfig
  public static KafkaProducer<String, String> producer;

  @Test
  public void myTest() {
    // producer.send(...)
    // consumer.poll(...)
  }
}

public class KafkaTestResourceConfig implements SharedContainerConfiguration {

  private static Network network = Network.newNetwork();

  @Container
  public static KafkaContainer kafka = new KafkaContainer("5.0.1")
    .withNetwork(network);
}

```
**Expected behavior**
Injection should work the way it does if you remove `@QuarkusTest` annotation.

**System information:**
 - OS: macOS 10.15.3
 - Java Version: 11
 - MicroShed Testing Version: 0.8.1-SNAPSHOT
 - Qarkus 1.3.2.Final

**Comment by aguibert** [comment]
hi @CrystalMethod, thanks for raising this issue. Which package are you importing the `KafkaConsumer` and `KafkaProducer` classes from? Microshed will only scan for fields of type `org.apache.kafka.clients.producer.KafkaConsumer` and `org.apache.kafka.clients.producer.KafkaProducer` respectively. 

My first guess is that perhaps you are importing these classes from other packages/APIs, such as `io.vertx.kafka.client.*`? In which case we should improve the Microshed docs and also add some more agressive error detection on fields annotated with `@KafkaConusmer/ProducerConfig`

**Comment by aguibert** [comment]
never mind, I see the issue now. This used to work with Quarkus 1.2.1.Final, but when I try with 1.3.2.Final then it the injection fails as you described.

It looks like `@QuarkusTest` was changed to load the test class in an isolated classloader:
 - `@MicroShedTest` processes the class used by the default JDK app classloader
 - `@QuarkusTest` creates a new "Quarkus Base Classloader"

Since the annotations run in order they are defined (microshed first, then quarkus test) the special Quarkus Classloader isn't created at the time Microshed gets to do its thing. Some how the test runs from the Quarkus Base Classloader's copy of the class, so I'll have to investigate further to see if there is any fix or workaround

**Comment by CrystalMethod** [comment]
Yes, when downgrading to Quarkus 1.2.1.Final the injection works as expected.

Sorry for not more emphasizing the used version of Quarkus. Starting with Quarkus version 1.3.0 the classloading mechanism was significantly reworked.
