### ISSUE TITLE
Tests all fail with mvn verify when there is an application tag in server.xml

### ISSUE THREAD

**Issue by vzorge** [MicroShed/microshed-testing#280]
**Describe the bug**
When using mvn liberty:dev the application and tests run perfectly. However, running the same tests with mvn verify fails, because the application is not deployed, testcontainer complains that it cannot find the war taht was just build.

**To Reproduce**
I found the reproduction to be a bit tricky. But I managed it as follows:
Check out the  https://github.com/openliberty/guide-microshed-testing.git openliberty guide
Alter the server.xml to look like this:
`<server>

    <featureManager>
        <feature>microProfile-4.0</feature>
        <feature>beanValidation-2.0</feature>
    </featureManager>

    <application location="guide-microshed-testing.war" type="war" context-root="guide-microshed-testing">
    </application>

</server>`

When I run _mvn clean install_ I get the following message:

> [ApplicationContainer] [WARNING ] CWWKZ0014W: The application guide-microshed-testing could not be started as it could not be found at location guide-microshed-testing.war.

And the tests all threw a 404 exception.

When removing the <application> tag, it will work properly.
The weird thing is, that I have seen it work when there was an <application> tag, but this is the minimal setup that I could reliably reproduce it. Sometimes adding and removing a feature seemed to make it work or fail, but I could not find any logic in it.

**Expected behavior**
I expect the test to succeed, since the .war was made just before in the package step:
>  [INFO] Building war: /home/vin/code/guide-microshed-testing/finish/target/guide-microshed-testing.war
And mvn liberty:dev also works just fine.

**System information:**
 - OS: Linux and Windows
 - Java Version: 8 and 11
 - MicroShed Testing Version: 0.9.1

**Additional context**
I had this in my own application, but managed to reproduce it in the microshed guide of openliberty. While trying to find the minimal reproduction recipe I did see it work and fail with the same configuration, so I hope that setup works correctly to reproduce.

**Comment by kathrynkodama** [comment]
@vzorge Could you please provide the output from running `mvn verify` or `mvn install` vs running the tests with `mvn liberty:dev`?

**Comment by vzorge** [comment]
Attached two log outputs. I now notice it seems to find the application twice when using mvn verify. Perhaps that is the root cause?
[liberty:dev](https://github.com/MicroShed/microshed-testing/files/7628281/dev.log)
[mvn verify](https://github.com/MicroShed/microshed-testing/files/7628282/verify.log)

**Comment by kathrynkodama** [comment]
Thanks @vzorge, we will investigate this further. I am able to intermittently reproduce the same issue with the steps above. The tests seem to fail with `mvn verify` or `mvn install` about half of the time. I wonder if the application is not being cleaned up properly. 

I did notice that cleaning up unused Docker images and removing the testcontainers image after a failing run seemed to help the tests pass on subsequent runs.

cc: @scottkurz @yeekangc

**Comment by scottkurz** [comment]
Before we get to the specific symptoms there's a basic problem here.

The built-in Dockerfile is building the apps into **dropins** rather than the **apps** dir like you'd use with explicit application config in server.xml, like you added.

If you're not supplying your own **Dockerfile** in your app project (which this guide is not), you're going to end up using a default Dockerfile that's programmatically embedded into the Liberty adapter [here](https://github.com/MicroShed/microshed-testing/blob/d042216589f84a60591787c11e2a04bf11006369/modules/liberty/src/main/java/org/testcontainers/containers/liberty/LibertyAdapter.java#L119-L134) which also aligns with the snippet documented at: https://microshed.org/microshed-testing/features/SupportedRuntimes.html.

That said.. I'm not sure I explained the exact symptom.  

But you're probably going to want to make the change to correctly align anyway.

So to fix this problem... I'd start make a Dockerfile and drop it in your project root, and code it to ADD or COPY the app into /config/apps rather than /config/dropins.   

Please see if that helps and let us know if you have issues/questions.

**Comment by vzorge** [comment]
@scottkurz Thank you for your reply, this fixed my issue. If I add a Dockerfile it now runs perfectly. 
I actually had a dockerfile before and removed it because it was not working with maven and the example did not have a Dockerfile. Your comment made me re-add it and fix the error that was in it (and not obvious to me at the time).

Would it be a good idea to have the example application add a rudimentary Dockerfile?

**Comment by scottkurz** [comment]
> Would it be a good idea to have the example application add a rudimentary Dockerfile?

Great idea:   opened https://github.com/OpenLiberty/guide-microshed-testing/issues/98

Glad to help !
