### ISSUE TITLE
Support Podman for container runtime 

### ISSUE THREAD

**Issue by amarm85** [MicroShed/microshed-testing#286]
As docker desktop is now paid license, Are you planning to support other container runtime like Podman which is free.

**Comment by appiepollo14** [comment]
@KyleAure correct me if I'm wrong. But this question is out of scope for MicroShed. This is because MicroShed uses TestContainers dependency. For testcontainers to use Podman instead of Docker, [this guide ](https://stackoverflow.com/questions/71549856/testcontainers-with-podman-in-java-tests) can be followed and doesn't require a change in the code right?
