### ISSUE TITLE
Running unit and integration tests side by side

### ISSUE THREAD

**Issue by KyleAure** [MicroShed/microshed-testing#8]
As a user of the system-test package, I want to be able to run integration tests (using system-test) and unit tests (using junit) against a single application at the same time. 

This functionally already works, but it is easy to configure incorrectly.  Therefore, additional documentation / examples may be necessary. 
- Create sample application (gradle or maven)
- Distinguish between `it` and `unit` test directories
- Distinguish between `org.junit.jupiter.api.Test` and `org.junit.Test` imports
- Write accompanying documentation.

**Comment by aguibert** [comment]
I think the confusion here is because we require the use of JUnit 5, which uses `@org.junit.jupiter.api.Test` for all tests, whereas JUnit 4 uses `@org.junit.Test`.

The system-test package doesn't do anything special for discovering/invoking tests -- we just let JUnit discover/run them. We can call out in the getting started doc that JUnit 5 must be used and highlight the different package for the `@Test` annotation though
